# Release new version to NPM when Pull requests are merged
name: Release

on:
  push:
    branches:
      - fix/chainify-version

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3.1.1
        with:
          node-version: 16

      - uses: actions/cache@v3.0.2
        id: cache
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-node${{ env.node-version }}

      - name: install dependencies
        run: yarn

      - name: Get date
        id: date
        run: |
          echo "::set-output name=date::$(date +%Y-%m-%d_%H-%M-%S)"

      - name: Create Release Pull Request & npm publish
        uses: changesets/action@v1
        id: changesets
        with:
          publish: yarn build-release
          commit: 'chore: entering prerelease mode'
          title: ':rocket: Release ${{ steps.date.outputs.date }} :rocket:'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create git tags
        if: steps.changesets.outputs.published == 'true'
        run: |
          echo 'steps.changesets.outputs.published'
          echo ${{ steps.changesets.outputs.published }}
          echo 'steps.changesets.outputs.published'
          echo ${{ steps.changesets.outputs.published }}
#          git tag -a v${{ env.version }} -m ":rocket: Release ${{ steps.date.outputs.date }} :rocket:"
#          git push origin v${{ env.version }}



